from irregular_verbs import *

a = [	
	("abroad", "extranjero"),
	("absent", "ausente"),
	("accountant", "contable"),
	("accurate", "precisa"),
	("ache", "dolor"),
	("achieve", "lograr"),
	("ad", "anuncio"),
	("admire", "admirar"),
	("advertise", "anunciar"),
	("advice", "consejo"),
	("advise", "aconsejar"),
	("afford", "permitirse"),
	("afraid", "asustado"),
	("afterwards", "después"),
	("aim", "objetivo"),
	("alike", "igual"),
	("almost", "casi"),
	("along", "a lo largo"),
	("also", "además"),
	("although", "a pesar de que"),
	("amazed", "asombrada"),
	("among", "entre"),
	("amusing", "divertido"),
	("ankle", "tobillo"),
	("announcement", "anuncio/declaración"),
	("annoy", "molestar"),
	("antique", "antiguo"),
	("anxious", "ansioso"),
	("any", "cualquiera (ninguna)"),
	("apart", "aparte"),
	("apologise", "disculparse"),
	("apology", "disculpa"),
	("appearance", "apariencia"),
	("appointment", "cita"),
	("approach", "acercarse"),
	("argue", "discutir"),
	("arrange", "organizar"),
	("arragement", "arreglo"),
	("ashamed", "avergonzado"),
	("as long as", "mientras"),
	("as well", "también"),
	("at once", "enseguida"),
	("attach", "adjuntar"),
	("attempt", "intento"),
	("attract", "atraer"),
	("aunt", "tía")
]

b = [
	("backwards", "hacia atrás"),
	("baggage", "equipaje"),
	("bake", "hornear"),
	("baker", "panadero"),
	("bald", "calvo"),
	("bandage", "vendaje"),
	("basin", "lavabo/palangana"),
	("bathing suit", "traje de baño"),
	("bathtub", "bañera"),
	("bay", "bahía"),
	("beard", "barba"),
	("behave", "comportarse"),
	("belong", "pertenecer a"),
	("below", "abajo"),
	("beneath", "debajo"),
	("beside", "al lado de"),
	("besides", "además"),
	("beyond", "más allá"),
	("bill", "factura"),
	("bin", "compartimiento"),
	("bite", "mordedura"),
	("bitter", "amargo"),
	("blame", "culpar"),
	("blanket", "manta"),
	("blouse", "blusa"),
	("boarding pass", "tarjeta de ambarque"),
	("boil", "hervir"),
	("boiled", "hervido"),
	("bookshelf", "estante de libros"),
	("borrow", "pedir prestado"),
	("bother", "molestia"),
	("bowl", "cuenco"),
	("brake", "freno"),
	("bread", "pan"),
	("breath", "aliento"),
	("breathe", "respirar"),
	("breeze", "brisa"),
	("bride", "novia(prometida)"),
	("brief", "breve"),
	("bright", "brillante"),
	("bring", "traer/llevar"),
	("bring up", "sacar un tema"),
	("broad", "ancho"),
	("brochure", "folleto"),
	("light bulb", "bombilla"),
	("bull", "toro"),
	("bunch", "manojo"),
	("bury", "enterrar"),
	("butcher", "carnicero"),
	("butter", "mantequilla"),
	("by hand", "manualmente")
]

c = [
	("cab", "taxi"),
	("cabbage", "repollo / col"),
	("cabinet", "gabinete"),
	("cage", "jaula"),
	("calf", "becerro"),
	("call for", "pedir"),
	("candle", "vela"),
	("canteen", "cantina"),
	("cardboard", "cartulina"),
	("career", "carrera"),
	("carry out", "llevar a cabo"),
	("case", "caso"),
	("ceiling", "techo"),
	("central heating", "calefacción central"),
	("certain", "cierto"),
	("changing room", "vestuario"),
	("charming", "encantador"),
	("cheap", "barato"),
	("cheat", "engañar"),
	("check", "cheque"),
	("check in", "registrarse"),
	("check out", "revisar"),
	("cheek", "mejilla"),
	("cheerful", "alegre"),
	("cheers!", "¡salud!"),
	("chest of drawers", "cajonera"),
	("chilli", "chile"),
	("chin", "barbilla"),
	("clap", "aplaudir"),
	("cliff", "acantilado"),
	("clothes", "ropa"),
	("coast", "costa"),
	("coat", "saco"),
	("cod", "bacalao"),
	("colleague", "colega"),
	("collet", "recoger"),
	("comb", "peine"),
	("compete", "competir"),
	("complain", "quejar"),
	("complaint", "queja"),
	("confident", "confiada"),
	("consider", "considerar"),
	("convince", "convencer"),
	("corn", "maiz"),
	("costume", "disfraz"),
	("cosy", "acogedor"),
	("cottage", "cabaña"),
	("cough", "tos"),
	("countryside", "campo"),
	("couple", "pareja"),
	("court", "corte (tribunal)"),
	("crew", "personal (trabajadores)"),
	("cricket", "grillo"),
	("crop", "cosecha"),
	("cross", "cruzar"),
	("crossing", "cruce"),
	("pedestrian crossing", "cruce peatonal"),
	("cross out", "tachar"),
	("crossroads", "encrucijada"),
	("crowd", "multitud"),
	("crowded", "concurrida"),
	("cruise", "crucero"),
	("cucumber", "pepino"),
	("cupboard", "alacena"),
	("curly", "rizada"),
	("currency", "moneda/divisa"),
	("curtain", "cortina"),
	("cushion", "amortiguar"),
	("customer", "cliente"),
	("customs", "aduana")

]

file_1 = [
    ("aubergine", "berenjena (n)"),
    ("avocado", "aguacate (n)"),
    ("baked", "al horno (adj)"),
    ("beans", "judías (pl n)"),
    ("beef", "ternera (n)"),
    ("beetroot", "remolacha (n)"),
    ("boiled", "cocido (adj)"),
    ("cabbage", "col (n)"),
    ("cherries", "cerezas (pl n)"),
    ("chicken", "pollo (n)"),
    ("courgette", "calabacín (n)"),
    ("crab", "cangrejo (n)"),
    ("cucumber", "pepino (n)"),
    ("duck", "pato (n)"),
    ("egg", "huevo (n)"),
    ("fish", "pescado (n)"),
    ("fried", "frito (adj)"),
    ("fruit", "fruta (n)"),
    ("grapes", "uvas (n)"),
    ("grilled", "a la parrilla (adj)"),
    ("lamb", "cordero (n)"),
    ("lemon", "limón (n)"),
    ("lobster", "langosta (n)"),
    ("mango", "mango (n)"),
    ("meat", "carne (n)"),
    ("melon", "melón (n)"),
    ("mussels", "mejillones (pl n)"),
    ("peach", "melocotón (n)"),
    ("pear", "pera (n)"),
    ("pepper", "pimiento (n)"),
    ("pork", "cerdo (n)"),
    ("potatoes", "patatas (pl n)"),
    ("prawns", "gambas (pl n)"),
    ("raspberries", "frambuesas (pl n)"),
    ("roast", "asado (adj)"),
    ("salmon", "salmón (n)"),
    ("seafood", "marisco (n)"),
    ("squid", "calamar (n)"),
    ("steamed", "al vapor (adj)"),
    ("tuna", "atún (n)"),
    ("vegetable", "verdura (n)"),
    ("affectionate", "cariñoso (adj)"),
    ("ambitious", "ambicioso (adj)"),
    ("anxious", "preocupado (adj)"),
    ("bossy", "mandón (adj)"),
    ("charming", "encantador (adj)"),
    ("competitive", "competitivo (adj)"),
    ("dishonest", "deshonesto (adj)"),
    ("disorganized", "desorganizado (adj)"),
    ("friendly", "amable/amigable (adj)"),
    ("honest", "honrado (adj)"),
    ("imaginative", "imaginativo (adj)"),
    ("immature", "inmaduro (adj)"),
    ("impatient", "impaciente (adj)"),
    ("independent", "independiente (adj)"),
    ("insecure", "inseguro (adj)"),
    ("insensitive", "insensible (adj)"),
    ("irresponsible", "irresponsable (adj)"),
    ("kind", "amable (adj)"),
    ("mature", "maduro (adj)"),
    ("moody", "de humor cambiante (adj)"),
    ("organized", "organizado (adj)"),
    ("patient", "paciente (adj)"),
    ("rebellious", "rebelde (adj)"),
    ("reliable", "de confianza (adj)"),
    ("responsible", "responsable (adj)"),
    ("self-confident", "seguro de sí mismo (adj)"),
    ("selfish", "egoísta (adj)"),
    ("sensible", "sensato (adj)"),
    ("sensitive", "sensible (adj)"),
    ("sociable", "sociable (adj)"),
    ("spoilt", "malcriado (adj)"),
    ("stubborn", "terco (adj)"),
    ("sympathetic", "compasivo (adj)"),
    ("tidy", "ordenado (adj)"),
    ("unambitious", "poco ambicioso (adj)"),
    ("unfriendly", "antipático (adj)"),
    ("unimaginative", "poco imaginativo (adj)"),
    ("unkind", "cruel (adj)"),
    ("unreliable", "poco fiable (adj)"),
    ("unselfish", "altruista (adj)"),
    ("unsociable", "poco sociable (adj)"),
    ("untidy", "desordenado (adj)"),
    ("cake", "pastel (n)"),
    ("cookie", "galleta (n)"),
    ("fresh", "fresco (adj)"),
    ("frozen", "congelado (adj)"),
    ("fruit salad", "ensalada de fruta (n)"),
    ("hot", "picante (adj)"),
    ("low-fat", "bajo en grasa (adj)"),
    ("onions", "cebollas (pl n)"),
    ("pasta", "pasta (pl n)"),
    ("pear", "pera (n)"),
    ("raw", "crudo (adj)"),
    ("spicy", "picante (adj)"),
    ("tinned", "en lata (adj)"),
    ("tomato", "tomate (n)"),
    ("Never mind", "No importa"),
    ("Go ahead", "Adelante"),
    ("Not really", "La verdad es que no"),
    ("Things like that", "Cosas así"),
    ("allergic", "alérgico (adj)"),
    ("cheer yourself up", "animarse"),
    ("filling", "relleno (n)"),
    ("generous", "generoso (adj)"),
    ("intolerant", "intolerante (adj)"),
    ("miss", "echar de menos (v)"),
    ("ready-made", "preparado (adj)"),
    ("rebellious", "rebelde (adj)"),
    ("takeaway", "para llevar (n)"),
    ("talkative", "hablador (adj)"),
    ("topping", "cobertura (n)")
]

file_2 = [
    ("afford", "(v) permitirse"),
    ("bill", "(n) factura"),
    ("borrow", "(v) pedir prestado"),
    ("budget", "(n) presupuesto"),
    ("charge", "(v) cobrar"),
    ("contactless payment", "(n) pago sin contacto"),
    ("cost", "(v) costar"),
    ("earn", "(v) ganar"),
    ("inherit", "(v) heredar"),
    ("insurance", "(n) seguro"),
    ("invest", "(v) invertir"),
    ("lend", "(v) prestar"),
    ("live off", "(phr v) vivir de"),
    ("live on", "(phr v) para vivir"),
    ("loan", "(n) préstamo"),
    ("mortgage", "(n) hipoteca"),
    ("note", "(n) billete"),
    ("owe", "(v) deber"),
    ("pay", "(v) pagar"),
    ("pay back", "(phr v) devolver"),
    ("raise", "(v) recaudar"),
    ("salary", "(n) salario"),
    ("save", "(v) ahorrar"),
    ("spend", "(v) gastar"),
    ("take out", "(phr v) sacar"),
    ("tax", "(n) impuestos"),
    ("waste", "(v) malgastar"),
    ("worth", "(adj) valer"),
    ("beauty treatment", "(n) tratamiento de belleza"),
    ("cash machine", "(n) cajero automático"),
    ("cleaning product", "(n) producto de limpieza"),
    ("cycling trip", "(n) ir en bicicleta"),
    ("electricity bill", "(n) factura de la electricidad"),
    ("olive oil", "(n) aceite de oliva"),
    ("tap water", "(n) agua del grifo"),
    ("amazed", "(adj) asombrado"),
    ("boiling", "(adj) hervir"),
    ("delighted", "(adj) encantado"),
    ("enormous", "(adj) enorme"),
    ("exhausted", "(adj) exhausto"),
    ("fascinating", "(adj) fascinante"),
    ("filthy", "(adj) muy sucio"),
    ("freezing", "(adj) congelarse"),
    ("furious", "(adj) furioso"),
    ("hilarious", "(adj) divertidísimo"),
    ("huge", "(adj) enorme"),
    ("positive", "(adj) seguro (positivo)"),
    ("starving", "(adj) morirse de hambre"),
    ("terrified", "(adj) aterrorizado"),
    ("tiny", "(adj) minúsculo"),
    ("scam", "(n) estafa")
]

file_3 = [
    ("car crash", "(n) accidente de tráfico (coche)"),
    ("coach", "(n) autocar"),
    ("cycle lane", "(n) carril bici"),
    ("end up", "(phr v) acabar"),
    ("ferry", "(n) ferry"),
    ("lorry", "(n) camión"),
    ("motorbike", "(n) motocicleta"),
    ("motorway", "(n) autovía"),
    ("parking fine", "(n) multa de aparcamiento"),
    ("pedestrian zone", "(n) zona peatonal"),
    ("petrol station", "(n) gasolinera"),
    ("pick up", "(phr v) recoger"),
    ("roadworks", "(n) obras"),
    ("run out", "(phr v) agotarse"),
    ("rush hour", "(n) hora punta"),
    ("scooter", "(n) scooter"),
    ("seat belt", "(n) cinturón de seguridad"),
    ("set off", "(phr v) marcharse"),
    ("speed camera", "(n) radar"),
    ("speed limit", "(n) límite de velocidad"),
    ("taxi rank", "(n) parada de taxis"),
    ("traffic jam", "(n) atasco"),
    ("traffic lights", "(n) semáforo"),
    ("tram", "(n) tranvía"),
    ("underground", "(n) Metro"),
    ("van", "(n) furgoneta"),
    ("zebra crossing", "(n) paso de cebra"),
    ("look out!", "¡cuidado!"),
    ("afraid of", "dar miedo (algo)"),
    ("angry with", "enfadado con"),
    ("apologize to", "disculparse por"),
    ("argue with", "discutir con"),
    ("arrive at", "llegar a"),
    ("arrive in", "llegar a (interrogativa)"),
    ("ask for", "pedir"),
    ("believe in", "creer en"),
    ("belong to", "pertenecer a"),
    ("choose between", "elegir entre"),
    ("close to", "cerca de"),
    ("depend on", "depender de"),
    ("different from", "diferente de"),
    ("dream about", "soñar con"),
    ("excited about", "emocionado por"),
    ("famous for", "famoso por"),
    ("fed up with", "harto de"),
    ("fond of", "aficionado a"),
    ("frightened of", "temeroso de"),
    ("good at", "bueno en"),
    ("good for", "bueno para"),
    ("interested in", "interesado en"),
    ("keen on", "entusiasta de"),
    ("kind to", "amable con"),
    ("laugh at", "reírse de"),
    ("look forward to", "estar deseando"),
    ("married to", "casarse con"),
    ("pay for", "pagar por"),
    ("pleased with", "contento con"),
    ("proud of", "orgulloso de"),
    ("remind (subject) of", "recordarle (algo) a (alguien)"),
    ("rude to", "grosero con"),
    ("scared of", "asustarse de"),
    ("spend money on", "gastar dinero en"),
    ("talk about", "hablar de"),
    ("talk to", "hablar a"),
    ("tired of", "cansado de"),
    ("worried about", "preocupado por"),
    ("I agree", "estoy de acuerdo"),
    ("personally", "personalmente"),
    ("come back", "volver"),
    ("kind of", "amable de (mi/tu/su/nuestra/vuestra) parte"),
    ("ahead of", "por delante de"),
    ("argue", "(v) discutir"),
    ("crash into", "chocar con"),
    ("discover", "(v) descubrir"),
    ("find", "(v) encontrar"),
    ("generally", "(adv) generalmente"),
    ("get stuck", "(phr v) quedarse atrapado"),
    ("get worse", "(phr v) empeorar"),
    ("in general", "en general"),
    ("likely", "(adj) probable"),
    ("on the whole", "en conjunto"),
    ("prove", "(v) demostrar"),
    ("show", "(v) mostrar"),
    ("tend", "(v) tender"),
    ("turn around", "(phr v) dar la vuelta"),
    ("turn out", "(phr v) resultar"),
    ("turn red", "ponerse en rojo"),
    ("usually", "normalmente")
]

file_4 = [
    ("call back", "(phr v) devolver una llamada"),
    ("cut off", "(phr v) cortarse"),
    ("dialling", "(v) marcar"),
    ("engaged", "ocupado"),
    ("go off", "(phr v) salir disparado"),
    ("hang up", "(phr v) colgar"),
    ("leave a message", "dejar un mensaje"),
    ("messaging", "(v) enviar mensajes"),
    ("monthly contract", "contrato mensual"),
    ("pay as you go", "pago sobre la marcha"),
    ("phone network", "(n) red telefónica"),
    ("put on hold", "poner en espera"),
    ("ringtone", "(n) tono de llamada"),
    ("send a text message", "enviar un SMS"),
    ("swiping", "(v) pasar"),
    ("voicemail", "(n) buzón de voz"),
    ("amazed", "(adj) asombrado"),
    ("amazing", "(adj) asombroso"),
    ("bored", "(adj) aburrido (alguien)"),
    ("boring", "(adj) aburrido (algo)"),
    ("depressed", "(adj) deprimido"),
    ("depressing", "(adj) deprimente"),
    ("disappointed", "(adj) decepcionado"),
    ("disappointing", "(adj) decepcionante"),
    ("embarrassed", "(adj) avergonzado"),
    ("embarrassing", "(adj) embarazoso"),
    ("excited", "(adj) emocionado"),
    ("exciting", "(adj) emocionante"),
    ("frightened", "(adj) aterrorizado"),
    ("frightening", "(adj) aterrador"),
    ("frustrated", "(adj) frustrado"),
    ("frustrating", "(adj) frustrante"),
    ("tired", "(adj) cansado (alguien)"),
    ("tiring", "(adj) cansado (algo)"),
    ("appropriate", "(adj) adecuado"),
    ("bad manners", "malos modales"),
    ("busking", "(n) actuación en la calle"),
    ("decline", "(v) rechazar"),
    ("give permission", "dar permiso"),
    ("inappropriate", "(adj) inadecuado"),
    ("inconsiderate", "(adj) desconsiderado"),
    ("monopolize", "(v) monopolizar"),
    ("musical instruments", "(pl n) instrumentos musicales"),
    ("octave", "(n) octava"),
    ("rude", "(adj) maleducado"),
    ("selfish", "(adj) egoísta"),
    ("tune", "(n) melodía")
]

file_5 = [
    ("beat", "(v) derrotar"),
    ("captain", "(n) capitán"),
    ("circuit", "(n) circuito"),
    ("course", "(n) campo (golf)"),
    ("court", "(n) cancha"),
    ("draw", "(v) empatar"),
    ("fan", "(n) forofo"),
    ("get fit", "ponerse en forma"),
    ("get injured", "lesionarse"),
    ("kick", "(v) dar una patada a"),
    ("knock out", "(phr v) eliminar (noquear)"),
    ("lose", "(v) perder"),
    ("pitch", "(n) campo (en deportes)"),
    ("player", "(n) jugador"),
    ("pool", "(n) piscina"),
    ("referee", "(n) árbitro"),
    ("score", "(v) marcar (puntaje)"),
    ("send off", "(phr v) expulsar"),
    ("slope", "(n) pista (esqui)"),
    ("spectator", "(n) espectador"),
    ("sports hall", "(n) pabellón deportivo"),
    ("stadium", "(n) estadio"),
    ("team", "(n) equipo"),
    ("throw", "(v) lanzar"),
    ("track", "(n) pista"),
    ("train", "(v) tren"),
    ("warm up", "(phr v) calentar"),
    ("win", "(v) ganar"),
    ("work out", "(phr v) entrenar"),
    ("break up", "(phr v) romper"),
    ("classmate", "(n) compañero de clase"),
    ("close friend", "(n) íntimo amigo"),
    ("colleague", "(n) compañero"),
    ("couple", "(n) pareja (de dos)"),
    ("ex", "(n) ex"),
    ("fancy", "(v) gustar (romántico)"),
    ("fiancé", "(n) prometido"),
    ("fiancée", "(n) prometida"),
    ("flatmate", "(n) compañero de piso"),
    ("get in touch", "ponerse en contacto"),
    ("get married", "casarse"),
    ("get on", "(phr v) llevarse"),
    ("get to know", "llegar a conocer"),
    ("go out together", "salir juntos"),
    ("have something in common", "tener algo en común"),
    ("lose touch", "perder el contacto"),
    ("meet", "(v) conocer (personas)"),
    ("partner", "(n) pareja"),
    ("propose", "(v) proponer matrimonio")
]

file_6 = [
    ("action film", "(n) película de acción"),
    ("animation", "(n) animación"),
    ("audience", "(n) público"),
    ("based on", "basado en"),
    ("cast", "(n) reparto"),
    ("comedy", "(n) comedia"),
    ("direct", "(v) directo"),
    ("drama", "(n) drama"),
    ("dub", "(v) doblar"),
    ("extra", "(n) figurante"),
    #("film on location", "rodar en exteriores"),
    ("historical film", "(n) película histórica"),
    ("horror film", "(n) película de terror"),
    ("musical", "(n) musical"),
    ("play the part of", "interpretar el papel de"),
    ("plot", "(n) argumento"),
    ("review", "(n) reseña"),
    ("rom-com", "(n) comedia romántica"),
    ("scene", "(n) escena"),
    ("science fiction film", "(n) película de ciencia ficción"),
    ("script", "(n) guión"),
    ("sequel", "(n) continuación"),
    ("set", "(v) situar"),
    ("shoot on location", "rodar en exteriores"),
    ("soundtrack", "(n) banda sonora"),
    ("special effects", "(pl n) efectos especiales"),
    ("star", "(n) estrella"),
    ("subtitles", "(pl n) subtítulos"),
    ("thriller", "(n) obra de suspense"),
    ("trailer", "(n) tráiler"),
    ("war film", "(n) película bélica"),
    ("western", "(n) película del oeste"),
    ("arms", "(pl n) brazos"),
    ("back", "(n) espalda"),
    ("bite", "(v) morder"),
    ("chin", "(n) barbilla"),
    ("clap", "(v) aplaudir"),
    ("ears", "(pl n) orejas"),
    ("eyes", "(pl n) ojos"),
    ("face", "(n) cara"),
    ("feet", "(pl n) pies"),
    ("fingers", "(pl n) dedos"),
    ("foot", "(n) pie"),
    ("hair", "(n) cabello"),
    ("hands", "(pl n) manos"),
    ("head", "(n) cabeza"),
    ("kick", "(v) dar una patada a"),
    ("knees", "(pl n) rodillas"),
    ("legs", "(pl n) piernas"),
    ("lips", "(pl n) labios"),
    ("mouth", "(n) boca"),
    ("neck", "(n) cuello"),
    ("nod", "(v) asentir con la cabeza"),
    ("nose", "(n) nariz"),
    ("point", "(v) señalar"),
    ("shoulders", "(pl n) hombros"),
    ("smell", "(v) oler"),
    ("smile", "(v) sonreír"),
    ("stare", "(v) mirar fijamente"),
    ("stomach", "(n) estómago"),
    ("taste", "(v) probar"),
    ("teeth", "(pl n) dientes"),
    ("throw", "(v) lanzar"),
    ("thumb", "(n) pulgar"),
    ("toes", "(pl n) dedos de los pies"),
    ("tongue", "(n) lengua"),
    ("tooth", "(n) diente"),
    ("touch", "(v) tocar"),
    ("whistle", "(v) silbar"),
    ("charisma", "(n) carisma"),
    ("epic", "(n) épico"),
    ("on set", "en el escenario")
]

miscellaneous = [
    ("hooded", "encampuchado"),
    ("knee-length", "hasta la rodilla"),
    ("leather", "cuero"),
    ("the latest", "lo último"),
    ("tight-fitting", "ajustados/apretados"),
    ("belt", "cinturón"),
    ("buckle", "hebilla"),
    ("catwalk", "pasarela/pasadizo"),
    ("fabric", "tela (materia prima)"),
    ("cloth", "tela (elaborada)"),
    ("make up", "maquillaje"),
    ("tan", "bronceado/broncearse"),
    ("borrow", "pedir prestado"),
    ("vanish", "desvanecerse"),
    ("vanish into thin air", "desaparecen sin dejar rastro"),
    ("felt", "fieltro"),
    ("nowadays", "hoy en día"),
    ("fair enough", "me parece justo"),
    ("aside from", "aparte de"),
    ("as for", "en cuanto a"),
    ("frankly", "francamente"),
    ("turnip", "nabo"),
    ("taste", "gusto (sentido)"),
    ("chop", "chuleta"),
    ("anything goes", "todo vale"),
    ("rub", "frotar/restregar"),
    ("serve", "servir (repartir comida / atender)"),
    ("fed up", "harto"),
    ("chickpeas", "garbanzos"),
    ("lentils", "lentejas"),
    ("grapefruit", "pomelo"),
    ("fare", "tarifa"),
    ("impolite", "descortés/maleducado"),
    ("garlic", "ajo"),
    ("bulb of garlic", "cabeza de ajo"),
    ("clove of garlic", "diente de ajo"),
    ("twice", "dos veces / doble"),
    ("convinced", "convencido")
]

expresions = [
    ("How fantastic!", "¡Es fantástico!"),
    ("Really?", "¿De verdad?"),
    ("What a great idea!", "¡Qué gran idea!"),
    ("What a pity!", "¡Qué pena!"),
    ("You're kidding", "Estás de broma"),
    ("He's a really nice guy", "Es un chico estupendo"),
    ("How do you see...", "¿Cómo ves...?"),
    ("How incredible!", "¡Es increíble!"),
    ("I mean...", "Quiero decir que..."),
    ("That's because", "Eso es porque"),
    ("don't you agree?", "¿no crees?"),
    ("i don't think that's right.", "no creo que sea así"),
    ("if you ask me, …", "si quieres saber mi opinión, …"),
    ("in my opinion", "en mi opinión"),
    ("oh, sure", "oh, claro que sí"),
    ("to be honest", "si he de ser sincero"),
    ("what do you think?", "¿qué opinas?"),
    ("did you mean", "¿querías decir"),
    ("it's just that", "es solo que"),
    ("oh, hang on a minute.", "oh, aguarda un minuto."),
    ("It's great to see you, mate", "Me alegro de verte, tío"),
    ("Just like the old days", "Igual que en los viejos tiempos"),
    ("No way", "No puede ser"),
    ("We've got lots to talk about", "Tenemos mucho de lo que hablar"),
    ("Another reason is", "Otro motivo es"),
    ("because", "porque"),
    ("For example,", "Por ejemplo,"),
    ("For instance,", "Por ejemplo,"),
    ("friendship", "amistad"),
    ("How amazing!", "¡Es asombroso!"),
    ("I'm going to talk about", "Voy a hablar sobre…"),
    ("I'm going to tell you about a time when", "Os voy a hablar de una vez que…"),
    ("I think the main reason is", "Creo que el principal motivo es"),
    ("leadership", "liderazgo"),
    ("membership", "afiliación"),
    ("partnership", "asociación"),
    ("Really?", "¿De verdad?"),
    ("relationship", "relación"),
    ("That sounds terrible", "Suena terrible"),
    ("This happened a few years ago", "Esto ocurrió hace algunos años"),
    ("What happened next?", "¿Qué ocurrió después?"),
    ("When I was younger", "Cuando yo era más joven,…"),
    ("Wow!", "¡Guau!"),
    ("Can you", "¿Puedes…?"),
    ("Could you do me a big favour?", "¿Podrías hacerme un enorme favor?"),
    ("Do you mind", "¿Te importa?"),
    ("Is it OK if", "¿Te parece bien que…?"),
    ("No problem", "No hay problema"),
    ("Not at all", "Para nada"),
    ("Of course not", "Por supuesto que no"),
    ("Sure", "Claro que sí"),
    ("Would you mind", "¿Te importaría…?"),
    ("How come", "¿Cómo es que…?"),
    ("If you don't mind", "Si no te importa"),
    ("Don't get me wrong", "No me malinterpretes"),
    ("I see what you mean", "Veo a que te refieres"),
    #("You've got a point there", "Tienes un punto válido")
]

tonari = [
	("mugging", "asalto"),
	("flown", "volado"),
	("misunderstanding", "malentendido"),
	("regard", "considerar"),
	("to be honest", "para ser honesto"),
	("pointless", "inútil"),
	("shaken", "agitado"),
	("aside", "aparte"),
	("sluggish", "lento/cansino/parsimónico"),
	("until", "hasta/hasta que"),
	("get-together", "reunirse"),
	("therefore", "por lo tanto"),
	("redeeming", "(adj) que redime / un punto positivo"),
	("treat", "tratar"),
	("beg", "mendigar/suplicar"),
	("reject", "rechazar"),
	("encourage", "alentar/animar"),
	("stare", "mirar fijamente"),
	("restless", "inquieto"),
	("despair", "desesperación"),
	("grasp", "sujetar"),
	("despite", "a pesar de"),
	("bewildered", "desconcertado"),
	("settled", "colocado/arreglado/apañado"),
	("soundly", "sólidamente"),
	("rooftop", "azotea"),
	("outrageous", "indignante"),
	("rely", "confiar"),
	("chicken coop", "gallinero"),
	("whim", "capricho"),
	("since", "ya que / desde que"),
	("hanging out", "pasar el rato"),
	("weird", "extraño"),
	("kindness", "amabilidad/bondad"),
	("nonsense", "disparates"),
	("awful", "horrible"),
	("messed up", "hecho un desastre"),
	("fright", "susto"),
	("squeeze", "apretar"),
	("troublesome", "molesto"),
	("kindred", "parientes"),
	("granny", "abuelita"),
	("bold", "atrevido"),
    ("pickles", "pepinillos"),
    ("lit up", "iluminado"),
    ("delight", "deleite/alegría"),
    ("mess around", "enredar/tontear"),
    ("shred", "trozo/jirón"),
    ("glared", "mirar fijamente"),
    ("menacing", "amenazante"),
    ("menacingly", "amenazadoramente"),
    ("jealousy", "celos"),
    ("jealous", "celoso"),
    ("at all", "en absoluto"),
    ("realised", "darse cuenta de"),
    ("keep this up", "seguir con esto"),
    ("owe", "deber (deuda)"),
    ("that's over the top", "eso es exagerado"),
    ("find out", "descubrir / averiguar"),
    ("cocky", "engreido (gallito)"),
    ("quell", "calmar"),
    ("get involved", "involucrarse"),
    ("regain", "recuperar"),
    ("I realise now", "me doi cuenta ahora"),
    ("tender", "tierno"),
    ("wipe", "limpiar (pasando un trapo / frotando)"),
    ("dirt", "suciedad"),
    ("tingle", "hormigueo"),
    ("settled", "establecido"),
    ("togs", "ropa (traje de baño / trapos)"),
    ("swore", "jurar"),
    ("misunderstood", "incomprendido"),
    ("nonetheless", "No obstante / sin embargo"),
    ("relief", "alivio"),
    ("I get it", "lo pillo"),
    ("repay", "retribuir"),
    ("somehow", "de alguna manera"),
    ("daring", "osado"),
    ("spread", "propagar / difundir"),
    ("don't spread it to me", "no me lo pegues (enfermedad / virus)"),
    ("eel", "anguila")
]

words_list = [] + tonari#file_6 #group_3 + group_2 + group_1# file_3 + file_4 + file_5 #+ a + b + c
